Server nicknames
sandialabs/wiretap pull request #48
Opened 2024-08-06 23:21 UTC by Aptimex

Deployed servers can now be given nicknames which will be displayed in the `status` command.

2024-08-07 05:35 UTC, luker983 commented on src/cmd/add_server.go
> +	err = serverConfigRelay.SetNickname(c.nickname)
Clients have entries for *every* server in their E2EE config, but only relay nodes in their Relay config. Why not have the nickname associated with the E2EE config?

2024-08-07 05:35 UTC, luker983 commented on src/cmd/status.go
> +		//nickname    string
Leftover comment

2024-08-07 05:35 UTC, luker983 commented on src/cmd/status.go
> +				//nickname: "12345678901234567890",
Leftover comment

2024-08-07 05:35 UTC, luker983 commented on src/peer/config.go
> +	if relayConfig.nickname != "" {
It may be desirable to keep nicknames client side only (less information disclosure to server nodes). Up to you, but if the servers don't *need* the nickname I'd keep them local.

2024-08-07 06:02 UTC, Aptimex commented on src/cmd/add_server.go
> +	err = serverConfigRelay.SetNickname(c.nickname)
Can arbitrary non-wireguard data go in those config files? I thought they had to conform to the standard Wireguard file format. If not then yeah, that's a much better place for them.

2024-08-07 23:48 UTC, Aptimex commented on src/cmd/add_server.go
> +	err = serverConfigRelay.SetNickname(c.nickname)
Remembered you can put comments in the files, which can be used to store info like that.

2024-08-07 23:49 UTC, Aptimex commented
Got the nicknames stored in the E2EE config file instead; still need to actually test that it works with `status`, and probably still need more changes to make it work with the `add server` command.

2024-08-08 05:15 UTC, luker983 commented on src/cmd/add_server.go
> +	err = serverConfigRelay.SetNickname(c.nickname)
Yeah, comments were what I had in mind for local config data that isn't part of the proper WG config

2024-08-19 22:42 UTC, Aptimex commented
Got everything working client-side. Let me know if you have any other feedback now.

2024-08-23 03:50 UTC, luker983 requested changes
Looks good! Left a few small comments but overall the client-side version is really clean!

2024-08-23 03:50 UTC, luker983 commented on src/peer/peer_config.go
> +	if p.nickname != "" {
Nickname seems like a useful field to have right above or below the `[Peer]` line as a reminder of what the peer is rather than the last field in the block

2024-08-23 03:50 UTC, luker983 commented on src/peer/peer_config.go
> +		s.WriteString(fmt.Sprintf("%sNickname = %s\n", CUSTOM_PREFIX, p.nickname))
nit: space after the comment would be easier on the eyes imo `#@ Nickname = ...`

2024-08-23 03:50 UTC, luker983 commented on src/peer/config.go
> +				if line[:2] == CUSTOM_PREFIX { //special wiretap-specific values
This will panic if the string is of length one (if there's a whitespace character), consider `strings.HasPrefix()`: https://pkg.go.dev/strings#HasPrefix

2024-08-23 03:50 UTC, luker983 commented on src/peer/config.go
> +const CUSTOM_PREFIX = "#@"
I like it 👍

2024-08-23 17:30 UTC, merged