Add --config-file to `serve`
sandialabs/wiretap pull request #7
Opened 2023-03-14 08:52 UTC by DennyDai

It might not be a good idea to expose a private key in command line arguments on a server that other users may have access to, so I added the `--config-file` option. 

The config file follows the same pattern as the WireGuard config file, but it has been modified to fit the wiretap arguments.

2023-03-16 23:32 UTC, luker983 commented
Hey, thanks for the PR! Great feature.

I think you could probably just swap out all of the config parsing for the existing library https://github.com/spf13/viper. It seems to be intended for this purpose (https://github.com/spf13/cobra/blob/main/user_guide.md) and it supports the INI format.

There is a feature in the works that will require the server to run two virtual interfaces, each with their own keys. This is going to require adding many more server-side args and I expect that your proposed config parser will become unwieldy once that gets merged.

Another suggestion is to make printing/writing the server config optional. Mostly for the same reason because once more args are added, writing the config to stdout will get messy.

Let me know what you think

2023-03-17 01:11 UTC, DennyDai commented
Thanks for the comments!

> Use viper

Yes that would the best approach in the long run in my opinion. 
I wasn't sure if you would be okay with using an additional library, but if you are it would make things a lot easier :)

> make printing server config optional

Considering that command-line arguments may not be a secure approach, especially in multi-user environments without root access, would you consider phasing out the use of command-line arguments? Wiretap could still support command-line arguments in the `serve` command for backward compatibility, but no longer print them in the `configure` command's output.

Since both the server and client configurations could be eventually stored as files, rather than having the option to print them to stdout, could we provide options (with default values of maybe just `server.conf` and `client.conf`) to output them directly to configuration files? (For example, `./wiretap configure ... --server-config-output abc.conf --client-config-output def.conf`) This would leave stdout only showing logs and instructions.

Let me know if this suggestion makes sense, and I'm happy to make any necessary updates to the PR :)

2023-03-17 02:36 UTC, luker983 commented
> I wasn't sure if you would be okay with using an additional library, but if you are it would make things a lot easier :)

Sounds good, Viper it is!

> Considering that command-line arguments may not be a secure approach, especially in multi-user environments without root access, would you consider phasing out the use of command-line arguments? Wiretap could still support command-line arguments in the `serve` command for backward compatibility, but no longer print them in the `configure` command's output.

I understand the concern, but for my use case the convenience of copy/paste greatly outweighs the risk of someone taking the private key and connecting to the client or decrypting traffic. Wiretap is meant to be a quick and dirty way of standing up tunnels in exceptional situations and copying a file isn't as quick as I would like. However, there may be some middle ground:
1. Pass arguments through stdin: `echo "-private ..." | ./wiretap`
2. Pass arguments through environment variables: `ARGS="-private ..." ./wiretap`

Neither of these should be visible to other users on a shared Linux box (I haven't tested on Windows), but they are logged in shell history. As an added bonus, Viper seems to support configs in environment variables. 

I can add a warning to the readme and move towards one of these options if they end up being viable?

> Since both the server and client configurations could be eventually stored as files, rather than having the option to print them to stdout, could we provide options (with default values of maybe just `server.conf` and `client.conf`) to output them directly to configuration files? (For example, `./wiretap configure ... --server-config-output abc.conf --client-config-output def.conf`) This would leave stdout only showing logs and instructions.

Yeah, it makes sense to directly output the server configuration to a file. `wiretap_server.conf` would be my preference as a default. The wiretap prefix helps keep all the files together. `-o,--output` is the current flag for client config file. `--server-config-output` would be good for the new flag.

2023-03-17 03:34 UTC, DennyDai commented
> Pass arguments through environment variables: ARGS="-private ..." ./wiretap
> but they are logged in shell history
> As an added bonus, Viper seems to support configs in environment variables.

Great idea! Using environment variables sounds like a plan. It's okay for them to be in the shell history since other non-root users won't have access to them.

---
Instead of using a single env var
```bash
ARGS="-private ..." ./wiretap
```
I would prefer
```bash
WIRETAP_PRIVATE_KEY="123456ABCEDEF" WIRETAP_ENDPOINT="127.0.0.1" ... ./wiretap
``` 
as it's a more common approach :)


I will be able to work on this over the weekend.

2023-03-17 17:48 UTC, luker983 commented
Sounds great, thank you!

2023-03-19 04:54 UTC, DennyDai commented
Hi, I have implemented what we discussed. Please let me know if you find any issues. :)

```bash
$ ./wiretap configure

Configuration successfully generated.
Import the config into WireGuard locally and pass the arguments below to Wiretap on the remote machine.

client config: wiretap.conf
────────────────────────────────
[Interface]
PrivateKey = OLkE9ws6TyFSWvrH4xlPi2Fnhhq+eq8+WtKbNowbcm0=
Address = 192.168.0.2/32
Address = fd::2/128
ListenPort = 51820

[Peer]
PublicKey = aPw0kyM+k7XtYbfoM5lK10Ywmns/EV1owiRrfUpISkU=
AllowedIPs = 0.0.0.0/32,a::/128
────────────────────────────────

server config: wiretap_server.conf

server command: WIRETAP_INTERFACE_PRIVATEKEY=CEiKIcb0I8WuUepbUlwY9sneeqOaBAyYVBvlRFsNY1A= WIRETAP_PEER_PUBLICKEY=B3HedkRZukaFhef9Fgpro8wwA4XKiFsnAPrHQAUGvFk= ./wiretap serve
```
```bash
$ cat wiretap_server.conf 
[Interface]
PrivateKey = CEiKIcb0I8WuUepbUlwY9sneeqOaBAyYVBvlRFsNY1A=
[Peer]
PublicKey = B3HedkRZukaFhef9Fgpro8wwA4XKiFsnAPrHQAUGvFk=
```
```bash
$ WIRETAP_INTERFACE_PRIVATEKEY=CEiKIcb0I8WuUepbUlwY9sneeqOaBAyYVBvlRFsNY1A= WIRETAP_PEER_PUBLICKEY=B3HedkRZukaFhef9Fgpro8wwA4XKiFsnAPrHQAUGvFk= ./wiretap serve

If needed, add this peer to your WireGuard configuration.

────────────────────────────────
[Peer]
PublicKey = aPw0kyM+k7XtYbfoM5lK10Ywmns/EV1owiRrfUpISkU=
AllowedIPs = 0.0.0.0/32
────────────────────────────────

private_key=08488a21c6f423c5ae51ea5b525c18f6c9de7aa39a040c98541be5445b0d6350
listen_port=51820
public_key=0771de764459ba468585e7fd160a6ba3cc300385ca885b2700fac7400506bc59
persistent_keepalive_interval=25

ERROR: 2023/03/19 00:50:01 peer(B3He…GvFk) - Failed to send handshake initiation: no known endpoint for peer
WIRETAP: 2023/03/19 00:50:01 Transport: UDP listener up
WIRETAP: 2023/03/19 00:50:01 Transport: ICMP listener up
WIRETAP: 2023/03/19 00:50:01 Transport: TCP listener up
WIRETAP: 2023/03/19 00:50:01 API: API listener up
^C
```
```bash
$ ./wiretap serve --config-file wiretap_server.conf 

If needed, add this peer to your WireGuard configuration.

────────────────────────────────
[Peer]
PublicKey = aPw0kyM+k7XtYbfoM5lK10Ywmns/EV1owiRrfUpISkU=
AllowedIPs = 0.0.0.0/32
────────────────────────────────

private_key=08488a21c6f423c5ae51ea5b525c18f6c9de7aa39a040c98541be5445b0d6350
listen_port=51820
public_key=0771de764459ba468585e7fd160a6ba3cc300385ca885b2700fac7400506bc59
persistent_keepalive_interval=25

ERROR: 2023/03/19 00:50:20 peer(B3He…GvFk) - Failed to send handshake initiation: no known endpoint for peer
WIRETAP: 2023/03/19 00:50:20 Transport: UDP listener up
WIRETAP: 2023/03/19 00:50:20 Transport: ICMP listener up
WIRETAP: 2023/03/19 00:50:20 Transport: TCP listener up
WIRETAP: 2023/03/19 00:50:20 API: API listener up
^C
```

2023-03-20 15:20 UTC, luker983 requested changes
Thank you for this! I'm very excited to get it merged. Along with the comments here, there are a couple things the linter caught

2023-03-20 15:20 UTC, luker983 commented on src/cmd/configure.go
> +}
Good call pulling this out 👍

2023-03-20 15:20 UTC, luker983 commented on src/cmd/configure.go
> +		err = clipboard.WriteAll(config.AsServerCommand())
As mentioned in another comment, I'd like to add a line with the Windows command line instructions, not sure the best way to incorporate clipboard... Maybe write both lines to clipboard?

2023-03-20 15:20 UTC, luker983 commented on src/cmd/configure.go
> +	fmt.Fprintln(color.Output, Green("./wiretap serve -f " + c.serverConfigFile))
I'd like the Windows command line here as well, I'm thinking:

```suggestion
	fmt.Fprintln(color.Output)
	fmt.Fprintln(color.Output, GreenBold("server command:"))
	fmt.Fprintln(color.Output, Cyan("   *nix:"), Green(config.AsServerCommand(NIX)))
	fmt.Fprintln(color.Output, Cyan("windows:"), Green(config.AsServerCommand(WINDOWS))
	fmt.Fprintln(color.Output, Cyan("   file:"), Green("./wiretap serve -f " + c.serverConfigFile))
```

2023-03-20 15:20 UTC, luker983 commented on src/cmd/serve.go
> +	cmd.Flags().IntP("mtu", "m", 1420, "tunnel MTU")
This section is marked deprecated, but still plays a pivotal role in setting the defaults for these options when not found by viper. What was the reason for moving the defaults from `serveCmd`/`serveCmdConfig` at the top of the file to here?

2023-03-20 15:20 UTC, luker983 commented on src/cmd/serve.go
> +
Very nice 😄

2023-03-20 15:20 UTC, luker983 commented on src/peer/config.go
> +}
Please add a way to print the Windows version of this. Something like `set WIRETAP_INTERFACE_PRIVATEKEY=%s & set WIRETAP_PEER_PUBLICKEY=%s & .\\wiretap serve`

2023-03-20 19:59 UTC, DennyDai commented on src/cmd/serve.go
> +	cmd.Flags().IntP("mtu", "m", 1420, "tunnel MTU")
I wanted to separate "serve command options" and "wiretap configs", but forgot the point that the setting the default is still a very important part of it.

How do you think about this: Create another struct and variable just to store the config defaults (or actually, should we consider reuse config.go?), and instead of setting the defaults here in deprecated flags, use viper.setDefault() to set default values.

2023-03-20 20:05 UTC, DennyDai commented on src/cmd/configure.go
> +	fmt.Fprintln(color.Output, Green("./wiretap serve -f " + c.serverConfigFile))
Oh, I didn't think of Windows at all. Sure, that would be nice. Do you want it to always show both Windows and *nix, or default to *nix with an extra option to show Windows?

2023-03-20 22:41 UTC, luker983 commented on src/cmd/configure.go
> +	fmt.Fprintln(color.Output, Green("./wiretap serve -f " + c.serverConfigFile))
I think always showing would be better. I can imagine users running it once, realizing they need the Windows output, then running again which might get annoying

2023-03-20 22:46 UTC, luker983 commented on src/cmd/serve.go
> +	cmd.Flags().IntP("mtu", "m", 1420, "tunnel MTU")
Oh okay, I see. Another struct and variable might be best so it's similar to the other commands

2023-03-20 23:36 UTC, DennyDai commented on src/peer/config.go
> +}
This method appears to work on Windows CMD, but not on PowerShell. PowerShell has become the default command shell on modern Windows systems for a while, should I use PowerShell or CMD or both?

2023-03-20 23:37 UTC, DennyDai commented on src/cmd/configure.go
> +	fmt.Fprintln(color.Output, Green("./wiretap serve -f " + c.serverConfigFile))
If we are going to use PowerShell here, rather than referring to them as *nix or Windows shells, should I distinguish between POSIX shell and PowerShell instead?

2023-03-20 23:56 UTC, luker983 commented on src/peer/config.go
> +}
Ah, darn. I think just one is fine, I don't care which one. `powershell.exe -c` or `cmd /C` can be used to translate as needed

2023-03-20 23:59 UTC, luker983 commented on src/cmd/configure.go
> +	fmt.Fprintln(color.Output, Green("./wiretap serve -f " + c.serverConfigFile))
Yeah whatever gets the point across works for me. I'd be comfortable with any of: `PS`, `PowerShell`, `Windows`

2023-03-21 00:25 UTC, DennyDai commented on src/cmd/configure.go
> +		err = clipboard.WriteAll(config.AsServerCommand())
I left it to be posix shell only as it's highly probable that the user will be on Linux. Writing both to clipboard doesn't work on either of the platform if user decide to directly paste it to the terminal.

2023-03-21 00:26 UTC, DennyDai commented
Thank you for reviewing! I have updated the code as you requested. :)

2023-03-21 23:38 UTC, DennyDai commented
Thank you, looking forward to seeing it merged!

2023-03-23 14:41 UTC, luker983 approved these changes

2023-03-23 14:44 UTC, merged

2023-03-23 14:45 UTC, luker983 commented on src/cmd/serve.go
> +				AllowedIPs:                  viper.GetStringSlice("Peer.allowed"),
There was a bug where `allowed` wasn't being parsed properly. Switching to `GetStringSlice()` rather than `Split(GetString(), ',')` fixed it

2023-03-23 15:54 UTC, DennyDai commented on src/cmd/serve.go
> +				AllowedIPs:                  viper.GetStringSlice("Peer.allowed"),
I did this intentionally. when I used GetStringSlice(), it failed to parse comma separated list but maybe I was doing something wrong. Can you double check on it just to be sure?
You can find more information here: https://github.com/spf13/viper/issues/380
and this is the what I got after running latest version of wiretap `WIRETAP: 2023/03/23 11:50:29 failed to make configuration: invalid CIDR address: 10.0.***.0/24,192.168.***.0/24,192.168.***.0/24`

Thanks :)

2023-03-23 16:43 UTC, luker983 commented on src/cmd/serve.go
> +				AllowedIPs:                  viper.GetStringSlice("Peer.allowed"),
Can you provide the full command that gives you that error? 

The server was ignoring the AllowedIPs because it couldn't get a string from a string slice.

Right now with the new GetStringSlice, AllowedIPs need to be space-separated in the env variable, or comma separated in the command line arg to work unfortunately, but that seems to be a symptom of the Viper issue you linked

2023-03-23 16:46 UTC, DennyDai commented on src/cmd/serve.go
> +				AllowedIPs:                  viper.GetStringSlice("Peer.allowed"),
```bash
$ cat server.conf
[Interface]
PrivateKey = [redacted]
IPv4 = 10.0.22.6/32
[Peer]
PublicKey = [redacted]
Endpoint = [redacted]:51820
Allowed = 10.0.22.0/24,192.168.44.0/24,192.168.33.0/24

$ wiretap serve -f server.conf
...
```

2023-03-23 16:50 UTC, DennyDai commented on src/cmd/serve.go
> +				AllowedIPs:                  viper.GetStringSlice("Peer.allowed"),
If we aim for consistency by using comma-separated lists throughout, we may need to avoid using `GetStringSlice()`. `Split(GetString(), ',')` works on my end but I'm not sure whether this is the best way to do it.

2023-03-23 17:09 UTC, luker983 commented on src/cmd/serve.go
> +				AllowedIPs:                  viper.GetStringSlice("Peer.allowed"),
Proposed a hotfix for this in #8. Let me know if that addresses the concern